Revert "chore:CI/CD initial testing"
This reverts commit 1e7f8b1f0d65b466688208e89e469c3d0bdeacd3.
Error: reverting to the original code from version 0.1.3b